import type { DB } from './types';

/**
 * Seeded demo data. All people are FICTIONAL. All history, ratings and
 * "verified" flags are sample content for demonstration only.
 */
export const DB_VERSION = 3;

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export function buildSeed(): DB {
  return {
    version: DB_VERSION,
    users: [
      { id: 'stu-demo', role: 'student', name: 'Sara (Demo Student)', nameAr: 'سارة (طالبة تجريبية)', email: 'demo.student@example.com', avatarHue: 210, createdAt: now - 40 * day, isDemoSeed: true },
      { id: 'tch-ahmed', role: 'teacher', name: 'Ahmed (Demo Teacher)', nameAr: 'أحمد (معلم تجريبي)', email: 'demo.teacher@example.com', avatarHue: 160, createdAt: now - 200 * day, isDemoSeed: true },
      { id: 'tch-noura', role: 'teacher', name: 'Noura', nameAr: 'نورة', email: 'noura@example.com', avatarHue: 330, createdAt: now - 300 * day, isDemoSeed: true },
      { id: 'tch-khalid', role: 'teacher', name: 'Khalid', nameAr: 'خالد', email: 'khalid@example.com', avatarHue: 20, createdAt: now - 260 * day, isDemoSeed: true },
      { id: 'tch-mona', role: 'teacher', name: 'Mona', nameAr: 'منى', email: 'mona@example.com', avatarHue: 275, createdAt: now - 150 * day, isDemoSeed: true },
      { id: 'tch-omar', role: 'teacher', name: 'Omar', nameAr: 'عمر', email: 'omar@example.com', avatarHue: 45, createdAt: now - 120 * day, isDemoSeed: true },
    ],
    studentProfiles: [
      {
        userId: 'stu-demo',
        level: 'secondary',
        grade: 1,
        preferredSubjects: ['math', 'physics', 'english'],
        rating: 4.8,
        ratingCount: 6,
        walletBalance: 100,
      },
    ],
    teacherProfiles: [
      {
        userId: 'tch-ahmed',
        subjects: ['math', 'physics'],
        levels: ['intermediate', 'secondary'],
        bio: 'Mathematics and physics tutor focused on building real understanding, not memorization. I like starting from what the student already knows.',
        bioAr: 'معلم رياضيات وفيزياء أركز على الفهم الحقيقي لا الحفظ. أحب أن أبدأ مما يعرفه الطالب مسبقًا.',
        yearsExperience: 7,
        languages: ['ar', 'en'],
        rating: 4.9,
        ratingCount: 118,
        completedSessions: 132,
        demoVerified: true,
        online: false,
        totalEarnings: 4620,
      },
      {
        userId: 'tch-noura',
        subjects: ['arabic', 'english'],
        levels: ['primary', 'intermediate', 'secondary'],
        bio: 'Language tutor helping students read, write and speak with confidence.',
        bioAr: 'معلمة لغات أساعد الطلاب على القراءة والكتابة والتحدث بثقة.',
        yearsExperience: 9,
        languages: ['ar', 'en'],
        rating: 4.8,
        ratingCount: 201,
        completedSessions: 214,
        demoVerified: true,
        online: true,
        totalEarnings: 6890,
      },
      {
        userId: 'tch-khalid',
        subjects: ['chemistry', 'biology', 'science'],
        levels: ['intermediate', 'secondary'],
        bio: 'Science tutor. I use everyday examples to make chemistry and biology stick.',
        bioAr: 'معلم علوم. أستخدم أمثلة من الحياة اليومية لتثبيت مفاهيم الكيمياء والأحياء.',
        yearsExperience: 5,
        languages: ['ar'],
        rating: 4.7,
        ratingCount: 74,
        completedSessions: 81,
        demoVerified: true,
        online: true,
        totalEarnings: 2530,
      },
      {
        userId: 'tch-mona',
        subjects: ['math', 'science', 'arabic'],
        levels: ['primary'],
        bio: 'Primary-school specialist. Patient, structured and great with younger learners.',
        bioAr: 'متخصصة في المرحلة الابتدائية. صبورة ومنظمة وأجيد التعامل مع صغار المتعلمين.',
        yearsExperience: 11,
        languages: ['ar'],
        rating: 5.0,
        ratingCount: 96,
        completedSessions: 103,
        demoVerified: false,
        online: false,
        totalEarnings: 2380,
      },
      {
        userId: 'tch-omar',
        subjects: ['cs', 'math'],
        levels: ['intermediate', 'secondary'],
        bio: 'Computer science tutor — programming basics, digital skills and exam prep.',
        bioAr: 'معلم حاسب — أساسيات البرمجة والمهارات الرقمية والتحضير للاختبارات.',
        yearsExperience: 4,
        languages: ['ar', 'en'],
        rating: 4.6,
        ratingCount: 39,
        completedSessions: 45,
        demoVerified: false,
        online: true,
        totalEarnings: 1490,
      },
    ],
    requests: [],
    sessions: [
      {
        id: 'ses-seed-1',
        requestId: 'req-seed-1',
        studentId: 'stu-demo',
        teacherId: 'tch-noura',
        subjectId: 'english',
        level: 'secondary',
        grade: 1,
        topic: 'Essay structure',
        duration: 45,
        price: 28,
        teacherNet: 28,
        status: 'completed',
        createdAt: now - 6 * day,
        startedAt: now - 6 * day,
        endedAt: now - 6 * day + 45 * 60 * 1000,
        ratingByStudent: { stars: 5, feedback: 'Very clear explanations.', at: now - 6 * day },
        ratingByTeacher: { stars: 5, at: now - 6 * day },
        chat: [],
        isDemoSeed: true,
      },
      {
        id: 'ses-seed-2',
        requestId: 'req-seed-2',
        studentId: 'stu-demo',
        teacherId: 'tch-ahmed',
        subjectId: 'math',
        level: 'secondary',
        grade: 1,
        topic: 'Factoring polynomials',
        duration: 60,
        price: 35,
        teacherNet: 35,
        status: 'completed',
        createdAt: now - 13 * day,
        startedAt: now - 13 * day,
        endedAt: now - 13 * day + 60 * 60 * 1000,
        ratingByStudent: { stars: 5, at: now - 13 * day },
        ratingByTeacher: { stars: 4, at: now - 13 * day },
        chat: [],
        isDemoSeed: true,
      },
    ],
    transactions: [
      { id: 'tx-seed-1', userId: 'stu-demo', type: 'topup', amount: 100, noteKey: 'tx.topup', createdAt: now - 14 * day, status: 'completed' },
      { id: 'tx-seed-2', userId: 'stu-demo', type: 'session_payment', amount: -35, noteKey: 'tx.sessionPayment', noteParams: { subject: 'math' }, sessionId: 'ses-seed-2', createdAt: now - 13 * day, status: 'completed' },
      { id: 'tx-seed-3', userId: 'stu-demo', type: 'topup', amount: 63, noteKey: 'tx.topup', createdAt: now - 7 * day, status: 'completed' },
      { id: 'tx-seed-4', userId: 'stu-demo', type: 'session_payment', amount: -28, noteKey: 'tx.sessionPayment', noteParams: { subject: 'english' }, sessionId: 'ses-seed-1', createdAt: now - 6 * day, status: 'completed' },
      { id: 'tx-seed-5', userId: 'tch-ahmed', type: 'earning', amount: 35, noteKey: 'tx.earning', noteParams: { subject: 'math' }, sessionId: 'ses-seed-2', createdAt: now - 13 * day, status: 'completed' },
    ],
    notifications: [
      { id: 'ntf-seed-1', userId: 'stu-demo', key: 'notif.welcome', createdAt: now - 14 * day, read: true },
      { id: 'ntf-seed-2', userId: 'tch-ahmed', key: 'notif.welcomeTeacher', createdAt: now - 14 * day, read: true },
    ],
    reports: [],
  };
}
